In [1]:
import os
from dotenv import load_dotenv
from datetime import date, timedelta
import requests
import zipfile
import io
import logging
from datetime import date, timedelta
import pandas as pd
import numpy as np
import yfinance as yfinance
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score
from edinet_xbrl.edinet_xbrl_parser import EdinetXbrlParser

load_dotenv()
EDINET_API_KEY = os.getenv('EDINET_API_KEY')

In [2]:
def get_documents_by_date(target_date, doc_type='030000'):
    """
    指定した日付にEDINETで開示された書類一覧を取得し、
    指定doc_type(有報)を満たすdoc_idとedinet_codeのリストを返す。
    """
    if isinstance(target_date, date):
        date_str = target_date.strftime("%Y-%m-%d")
    else:
        date_str = target_date
    base_url = "https://disclosure.edinet-fsa.go.jp/api/v2/documents.json"
    params = {'date': date_str, 'type': 2,'Subscription-Key':EDINET_API_KEY}
    r = requests.get(base_url, params=params)
    r.raise_for_status()
    data = r.json()
    results = data.get('results', [])

    docs = []


    for d in results:
        if d.get('formCode') == doc_type and d.get('docTypeCode') == '120':
            docs.append(d)

    return docs

h = get_documents_by_date(date(2024, 6, 11),doc_type='030000')

In [11]:
doc_id = h[0]['docID']
periodEnd_date= date.fromisoformat(h[0]['periodEnd'])

In [55]:
h

[{'seqNumber': 132,
  'docID': 'S100TKQK',
  'edinetCode': 'E03575',
  'secCode': '83660',
  'JCN': '6160001000993',
  'filerName': '株式会社滋賀銀行',
  'fundCode': None,
  'ordinanceCode': '010',
  'formCode': '030000',
  'docTypeCode': '120',
  'periodStart': '2023-04-01',
  'periodEnd': '2024-03-31',
  'submitDateTime': '2024-06-11 10:05',
  'docDescription': '有価証券報告書－第137期(2023/04/01－2024/03/31)',
  'issuerEdinetCode': None,
  'subjectEdinetCode': None,
  'subsidiaryEdinetCode': None,
  'currentReportReason': None,
  'parentDocID': None,
  'opeDateTime': None,
  'withdrawalStatus': '0',
  'docInfoEditStatus': '0',
  'disclosureStatus': '0',
  'xbrlFlag': '1',
  'pdfFlag': '1',
  'attachDocFlag': '1',
  'englishDocFlag': '0',
  'csvFlag': '1',
  'legalStatus': '1'}]

In [12]:
import os
import io
import zipfile
import tempfile
import requests
import logging

def download_xbrl_file(doc_id,output_dir = "./xbrl/"):
    """

    """
    path = output_dir + doc_id + '/'
    
    base_url = "https://disclosure.edinet-fsa.go.jp/api/v2/documents"
    params = {
        'type': 1,
        'Subscription-Key': EDINET_API_KEY
    }
    
    try:
        response = requests.get(f"{base_url}/{doc_id}", params=params, stream=True)
        response.raise_for_status()
    except Exception as e:
        logging.error("EDINET APIからのダウンロードに失敗しました: %s", e)
        return None
    
    # try:
    # ダウンロードしたZIPアーカイブをメモリ上で読み込む
    
    z = zipfile.ZipFile(io.BytesIO(response.content))
    # 出力先ディレクトリの作成
    if not os.path.exists(path):
        os.makedirs(path)
            
    filename = doc_id + ".zip"
    with open(path+filename, 'wb') as f:    
        for chunk in response.iter_content(chunk_size=1024):
          f.write(chunk)

    with zipfile.ZipFile(path+filename) as zip_f:
        zip_f.extractall(path)


        # ZIP 内で拡張子が .xbrl のファイルを検索（大文字小文字区別しない）
        xbrl_files = [f for f in zip_f.namelist() if f.lower().endswith('.xbrl')]
        if not xbrl_files:
            logging.warning("doc_id=%s のZIP内にXBRLファイルが見つかりませんでした", doc_id)
            return None
        
        # 例として最初に見つかった XBRL ファイルの絶対パスを返す
        xbrl_file_rel_path = xbrl_files[0]
        current_directory = os.getcwd()
        xbrl_file_abs_path = os.path.join(current_directory + path[1:], xbrl_file_rel_path)
        
    return xbrl_file_abs_path

In [13]:
xbrl_file_abs_path = download_xbrl_file(doc_id)

In [37]:
import os
import pandas as pd
from arelle import Cntlr

def extract_financial_data(xbrl_file):
    # Arelle のコントローラ作成（ログ出力は標準出力に設定）
    cntlr = Cntlr.Cntlr(logFileName='logToPrint')
    
    # XBRL ファイルを読み込み
    modelXbrl = cntlr.modelManager.load(xbrl_file)
    
    # 抽出データを格納するリスト
    data = []
    
    # 各 fact から情報を抽出
    for fact in modelXbrl.facts:
        # 必要な情報例: コンセプト、値、単位、コンテキストID
        row = {
            'concept': fact.concept.qname.localName,
            'concept_jp':fact.concept.label(preferredLabel=None, lang='ja', linkroleHint=None), 
            'value': fact.value,
            'unit': fact.unitID if fact.unitID else '',
            'context': fact.contextID,

        }
        data.append(row)
    
    # リストを pandas DataFrame に変換
    df = pd.DataFrame(data)
    return df

def set_context_YYYY(context_str):
    """
    context の文字列に含まれるキーワードに基づいて、
    対象期を periodEnd から何年前か計算し、'YYYY' 形式で返す。
    """
    if "CurrentYear" in context_str:
        target_date = periodEnd_date
    elif "Prior1Year" in context_str:
        target_date = periodEnd_date.replace(year=periodEnd_date.year - 1)
    elif "Prior2Year" in context_str:
        target_date = periodEnd_date.replace(year=periodEnd_date.year - 2)
    elif "Prior3Year" in context_str:
        target_date = periodEnd_date.replace(year=periodEnd_date.year - 3)
    elif "Prior4Year" in context_str:
        target_date = periodEnd_date.replace(year=periodEnd_date.year - 4)
    else:
        # 対象外の場合は None を返す
        return None
    
    return target_date.strftime("%Y")

def set_context_NCM(context_str):
    """
    context の文字列に含まれるキーワードに基づいて、
    連結か非連結（単独）かを判断する。
    """
    if "NonConsolidatedMember" in context_str:
        return True
        
    return False


xbrl_path = xbrl_file_abs_path  # 解析対象の XBRL ファイルパスに変更
if os.path.exists(xbrl_path):
    df = extract_financial_data(xbrl_path)

else:
    print("XBRL ファイルが見つかりません:", xbrl_path)

In [57]:
df

,concept,concept_jp,value,unit,context,context_YYYY,context_NCM
0,NumberOfSubmissionDEI,提出回数,1,pure,FilingDateInstant,None,False
1,OrdinaryIncomeSummaryOfBusinessResults,経常収益,88871000000,JPY,Prior4YearDuration,2020,False
2,OrdinaryIncomeSummaryOfBusinessResults,経常収益,85715000000,JPY,Prior3YearDuration,2021,False
3,OrdinaryIncomeSummaryOfBusinessResults,経常収益,98306000000,JPY,Prior2YearDuration,2022,False
4,OrdinaryIncomeSummaryOfBusinessResults,経常収益,115289000000,JPY,Prior1YearDuration,2023,False
...,...,...,...,...,...,...,...
2248,OtherInformationFinancialStatementsEtcTextBlock,その他,"<p class=""smt_head3"" style=""orphans:0;widows:0...",,CurrentYearDuration,2024,False
2249,OverviewOfOperationalProceduresForSharesTextBlock,提出会社の株式事務の概要,"\n<h2 class=""smt_head1"">第６ 【提出会社の株式事務の概要】</h2>...",,FilingDateInstant,None,False
2250,InformationAboutParentCompanyEtcOfReportingCom...,提出会社の親会社等の情報,\n１ 【提出会社の親会社等の情報】当行は、法第24条の７第１項に規定する親会社等はございま...,,FilingDateInstant,None,False
2251,OtherReferenceInformationTextBlock,その他の参考情報,"\n<h3 class=""smt_head2"" style=""font-family:&ap...",,FilingDateInstant,None,False
2252,InformationAboutCompanyWhichProvidesGuaranteeT...,提出会社の保証会社等の情報,"\n<h1 class=""smt_head1"">第二部 【提出会社の保証会社等の情報】</h...",,FilingDateInstant,None,False

### assets = df[df['unit']=='JPY']
# assets = assets.copy()
# assets['context_YYYY'] = assets['context'].apply(set_context_YYYY)
# assets['context_NCM'] = assets['context'].apply(set_context_NCM)

df = df.copy()
df['context_YYYY'] = df['context'].apply(set_context_YYYY)
df['context_NCM'] = df['context'].apply(set_context_NCM)

2250    \n１ 【提出会社の親会社等の情報】当行は、法第24条の７第１項に規定する親会社等はございま...
Name: value, dtype: object

In [53]:
columns_to_check = ['concept_jp']

filtered_df = df[
    df[columns_to_check]
    .apply(lambda row: row.astype(str).str.contains("配当").any(), axis=1)
]

In [56]:
filtered_df

,concept,concept_jp,value,unit,context,context_YYYY,context_NCM
161,DividendPaidPerShareSummaryOfBusinessResults,１株当たり配当額,40.00,JPYPerShares,Prior4YearDuration_NonConsolidatedMember,2020,True
162,DividendPaidPerShareSummaryOfBusinessResults,１株当たり配当額,40.00,JPYPerShares,Prior3YearDuration_NonConsolidatedMember,2021,True
163,DividendPaidPerShareSummaryOfBusinessResults,１株当たり配当額,80.00,JPYPerShares,Prior2YearDuration_NonConsolidatedMember,2022,True
164,DividendPaidPerShareSummaryOfBusinessResults,１株当たり配当額,80.00,JPYPerShares,Prior1YearDuration_NonConsolidatedMember,2023,True
165,DividendPaidPerShareSummaryOfBusinessResults,１株当たり配当額,90.00,JPYPerShares,CurrentYearDuration_NonConsolidatedMember,2024,True
166,InterimDividendPaidPerShareSummaryOfBusinessRe...,１株当たり中間配当額,17.50,JPYPerShares,Prior4YearDuration_NonConsolidatedMember,2020,True
167,InterimDividendPaidPerShareSummaryOfBusinessRe...,１株当たり中間配当額,17.50,JPYPerShares,Prior3YearDuration_NonConsolidatedMember,2021,True
168,InterimDividendPaidPerShareSummaryOfBusinessRe...,１株当たり中間配当額,17.50,JPYPerShares,Prior2YearDuration_NonConsolidatedMember,2022,True
169,InterimDividendPaidPerShareSummaryOfBusinessRe...,１株当たり中間配当額,40.00,JPYPerShares,Prior1YearDuration_NonConsolidatedMember,2023,True
170,InterimDividendPaidPerShareSummaryOfBusinessRe...,１株当たり中間配当額,50.00,JPYPerShares,CurrentYearDuration_NonConsolidatedMember,2024,True
196,PayoutRatioSummaryOfBusinessResults,配当性向,0.1721,pure,Prior4YearDuration_NonConsolidatedMember,2020,True
197,PayoutRatioSummaryOfBusinessResults,配当性向,0.1771,pure,Prior3YearDuration_NonConsolidatedMember,2021,True
198,PayoutRatioSummaryOfBusinessResults,配当性向,0.2270,pure,Prior2YearDuration_NonConsolidatedMember,2022,True
199,PayoutRatioSummaryOfBusinessResults,配当性向,0.2655,pure,Prior1YearDuration_NonConsolidatedMember,2023,True
200,PayoutRatioSummaryOfBusinessResults,配当性向,0.2709,pure,CurrentYearDuration_NonConsolidatedMember,2024,True
372,TotalAmountOfDividendsDividendsOfSurplus,配当金の総額,2374000000,JPY,FilingDateInstant_Row1Member,None,False
373,DividendPerShareDividendsOfSurplus,１株当たり配当額,50.00,JPYPerShares,FilingDateInstant_Row1Member,None,False
374,TotalAmountOfDividendsDividendsOfSurplus,配当金の総額,1877000000,JPY,FilingDateInstant_Row2Member,None,False
375,DividendPerShareDividendsOfSurplus,１株当たり配当額,40.00,JPYPerShares,FilingDateInstant_Row2Member,None,False
733,TotalOfDividendsReceivedEquitySecuritiesOtherT...,受取配当金の合計額,2749000000,JPY,CurrentYearDuration,2024,False
736,TotalOfDividendsReceivedEquitySecuritiesNotLis...,受取配当金の合計額,,JPY,CurrentYearDuration,2024,False
857,InterestAndDividendsOnSecuritiesOIBNK,有価証券利息配当金,19024000000,JPY,Prior1YearDuration,2023,False
858,InterestAndDividendsOnSecuritiesOIBNK,有価証券利息配当金,25026000000,JPY,CurrentYearDuration,2024,False
948,DividendsFromSurplus,剰余金の配当,-4951000000,JPY,Prior1YearDuration_RetainedEarningsMember,2023,False
949,DividendsFromSurplus,剰余金の配当,-4951000000,JPY,Prior1YearDuration_ShareholdersEquityMember,2023,False
976,DividendsFromSurplus,剰余金の配当,-4951000000,JPY,Prior1YearDuration,2023,False
1007,DividendsFromSurplus,剰余金の配当,-4273000000,JPY,CurrentYearDuration_RetainedEarningsMember,2024,False
1008,DividendsFromSurplus,剰余金の配当,-4273000000,JPY,CurrentYearDuration_ShareholdersEquityMember,2024,False
1034,DividendsFromSurplus,剰余金の配当,-4273000000,JPY,CurrentYearDuration,2024,False
1145,CashDividendsPaidFinCF,配当金の支払額,-4951000000,JPY,Prior1YearDuration,2023,False
1146,CashDividendsPaidFinCF,配当金の支払額,-4273000000,JPY,CurrentYearDuration,2024,False
1344,InterestAndDividendsOnSecuritiesOIBNK,有価証券利息配当金,19994000000,JPY,Prior1YearDuration_NonConsolidatedMember,2023,True
1345,InterestAndDividendsOnSecuritiesOIBNK,有価証券利息配当金,25998000000,JPY,CurrentYearDuration_NonConsolidatedMember,2024,True
1467,DividendsFromSurplus,剰余金の配当,-4951000000,JPY,Prior1YearDuration_NonConsolidatedMember_Retai...,2023,True
1468,DividendsFromSurplus,剰余金の配当,-4951000000,JPY,Prior1YearDuration_NonConsolidatedMember_Retai...,2023,True
1469,DividendsFromSurplus,剰余金の配当,-4951000000,JPY,Prior1YearDuration_NonConsolidatedMember_Share...,2023,True
1516,DividendsFromSurplus,剰余金の配当,-4951000000,JPY,Prior1YearDuration_NonConsolidatedMember,2023,True
1550,DividendsFromSurplus,剰余金の配当,-4273000000,JPY,CurrentYearDuration_NonConsolidatedMember_Reta...,2024,True
1551,DividendsFromSurplus,剰余金の配当,-4273000000,JPY,CurrentYearDuration_NonConsolidatedMember_Reta...,2024,True
1552,DividendsFromSurplus,剰余金の配当,-4273000000,JPY,CurrentYearDuration_NonConsolidatedMember_Shar...,2024,True
1595,DividendsFromSurplus,剰余金の配当,-4273000000,JPY,CurrentYearDuration_NonConsolidatedMember,2024,True
1771,DividendPolicyTextBlock,配当政策,"<p style=""page-break-before:always; line-heigh...",,FilingDateInstant,None,False
2191,NotesRegardingDividendTextBlock,配当に関する注記,"<p class=""smt_text6"" style=""orphans:0;widows:0...",,Prior1YearDuration,2023,False
2194,NotesRegardingDividendTextBlock,配当に関する注記,"<p class=""smt_text6"" style=""orphans:0;widows:0...",,CurrentYearDuration,2024,False

In [73]:
from dotenv import load_dotenv
import os
from sshtunnel import SSHTunnelForwarder
from pymongo import MongoClient


# .envファイルをロードして環境変数を読み込む
load_dotenv()

# SSH接続情報（.envから読み込み）
SSH_HOST = os.getenv('SSH_HOST')
SSH_PORT = int(os.getenv('SSH_PORT', 22))
SSH_USERNAME = os.getenv('SSH_USERNAME')
SSH_PASSWORD = os.getenv('SSH_PASSWORD')

# MongoDB接続情報（.envから読み込み）
MONGO_HOST = os.getenv('MONGO_HOST', '127.0.0.1')
MONGO_PORT = int(os.getenv('MONGO_PORT', 27017))
DATABASE_NAME = 'test'
COLLECTION_NAME = 'collection'
    
def ssh_connection_and_write(df):
    tunnel = SSHTunnelForwarder(
        (SSH_HOST, SSH_PORT),
        ssh_username=SSH_USERNAME,
        ssh_password=SSH_PASSWORD,
        remote_bind_address=(MONGO_HOST, MONGO_PORT)
    )
    tunnel.start()
    try:
        local_port = tunnel.local_bind_port
        print(f"SSHトンネル確立: ローカルポート {local_port} がリモートの {MONGO_HOST}:{MONGO_PORT} にマッピングされました。")
        
        client = MongoClient('127.0.0.1', local_port)
        db = client[DATABASE_NAME]
        collection = db[COLLECTION_NAME]
        
        records = df.to_dict(orient='records')
        result = collection.insert_many(records)

    finally:
        tunnel.stop()
        
    return result.inserted_ids

ssh_connection_and_write(df)

SSHトンネル確立: ローカルポート 58551 がリモートの 127.0.0.1:27017 にマッピングされました。

[ObjectId('67b7f32f8d297929dd94aee1'),
 ObjectId('67b7f32f8d297929dd94aee2'),
 ObjectId('67b7f32f8d297929dd94aee3'),
 ObjectId('67b7f32f8d297929dd94aee4'),
 ObjectId('67b7f32f8d297929dd94aee5'),
 ObjectId('67b7f32f8d297929dd94aee6'),
 ObjectId('67b7f32f8d297929dd94aee7'),
 ObjectId('67b7f32f8d297929dd94aee8'),
 ObjectId('67b7f32f8d297929dd94aee9'),
 ObjectId('67b7f32f8d297929dd94aeea'),
 ObjectId('67b7f32f8d297929dd94aeeb'),
 ObjectId('67b7f32f8d297929dd94aeec'),
 ObjectId('67b7f32f8d297929dd94aeed'),
 ObjectId('67b7f32f8d297929dd94aeee'),
 ObjectId('67b7f32f8d297929dd94aeef'),
 ObjectId('67b7f32f8d297929dd94aef0'),
 ObjectId('67b7f32f8d297929dd94aef1'),
 ObjectId('67b7f32f8d297929dd94aef2'),
 ObjectId('67b7f32f8d297929dd94aef3'),
 ObjectId('67b7f32f8d297929dd94aef4'),
 ObjectId('67b7f32f8d297929dd94aef5'),
 ObjectId('67b7f32f8d297929dd94aef6'),
 ObjectId('67b7f32f8d297929dd94aef7'),
 ObjectId('67b7f32f8d297929dd94aef8'),
 ObjectId('67b7f32f8d297929dd94aef9'),
 ObjectId('67b7f32f8d297929dd94aefa'),
 ObjectId('67b7f32f8d297929dd94aefb'),
 ObjectId('67b7f32f8d297929dd94aefc'),
 ObjectId('67b7f32f8d297929dd94aefd'),
 ObjectId('67b7f32f8d297929dd94aefe'),
 ObjectId('67b7f32f8d297929dd94aeff'),
 ObjectId('67b7f32f8d297929dd94af00'),
 ObjectId('67b7f32f8d297929dd94af01'),
 ObjectId('67b7f32f8d297929dd94af02'),
 ObjectId('67b7f32f8d297929dd94af03'),
 ObjectId('67b7f32f8d297929dd94af04'),
 ObjectId('67b7f32f8d297929dd94af05'),
 ObjectId('67b7f32f8d297929dd94af06'),
 ObjectId('67b7f32f8d297929dd94af07'),
 ObjectId('67b7f32f8d297929dd94af08'),
 ObjectId('67b7f32f8d297929dd94af09'),
 ObjectId('67b7f32f8d297929dd94af0a'),
 ObjectId('67b7f32f8d297929dd94af0b'),
 ObjectId('67b7f32f8d297929dd94af0c'),
 ObjectId('67b7f32f8d297929dd94af0d'),
 ObjectId('67b7f32f8d297929dd94af0e'),
 ObjectId('67b7f32f8d297929dd94af0f'),
 ObjectId('67b7f32f8d297929dd94af10'),
 ObjectId('67b7f32f8d297929dd94af11'),
 ObjectId('67b7f32f8d297929dd94af12'),
 ObjectId('67b7f32f8d297929dd94af13'),
 ObjectId('67b7f32f8d297929dd94af14'),
 ObjectId('67b7f32f8d297929dd94af15'),
 ObjectId('67b7f32f8d297929dd94af16'),
 ObjectId('67b7f32f8d297929dd94af17'),
 ObjectId('67b7f32f8d297929dd94af18'),
 ObjectId('67b7f32f8d297929dd94af19'),
 ObjectId('67b7f32f8d297929dd94af1a'),
 ObjectId('67b7f32f8d297929dd94af1b'),
 ObjectId('67b7f32f8d297929dd94af1c'),
 ObjectId('67b7f32f8d297929dd94af1d'),
 ObjectId('67b7f32f8d297929dd94af1e'),
 ObjectId('67b7f32f8d297929dd94af1f'),
 ObjectId('67b7f32f8d297929dd94af20'),
 ObjectId('67b7f32f8d297929dd94af21'),
 ObjectId('67b7f32f8d297929dd94af22'),
 ObjectId('67b7f32f8d297929dd94af23'),
 ObjectId('67b7f32f8d297929dd94af24'),
 ObjectId('67b7f32f8d297929dd94af25'),
 ObjectId('67b7f32f8d297929dd94af26'),
 ObjectId('67b7f32f8d297929dd94af27'),
 ObjectId('67b7f32f8d297929dd94af28'),
 ObjectId('67b7f32f8d297929dd94af29'),
 ObjectId('67b7f32f8d297929dd94af2a'),
 ObjectId('67b7f32f8d297929dd94af2b'),
 ObjectId('67b7f32f8d297929dd94af2c'),
 ObjectId('67b7f32f8d297929dd94af2d'),
 ObjectId('67b7f32f8d297929dd94af2e'),
 ObjectId('67b7f32f8d297929dd94af2f'),
 ObjectId('67b7f32f8d297929dd94af30'),
 ObjectId('67b7f32f8d297929dd94af31'),
 ObjectId('67b7f32f8d297929dd94af32'),
 ObjectId('67b7f32f8d297929dd94af33'),
 ObjectId('67b7f32f8d297929dd94af34'),
 ObjectId('67b7f32f8d297929dd94af35'),
 ObjectId('67b7f32f8d297929dd94af36'),
 ObjectId('67b7f32f8d297929dd94af37'),
 ObjectId('67b7f32f8d297929dd94af38'),
 ObjectId('67b7f32f8d297929dd94af39'),
 ObjectId('67b7f32f8d297929dd94af3a'),
 ObjectId('67b7f32f8d297929dd94af3b'),
 ObjectId('67b7f32f8d297929dd94af3c'),
 ObjectId('67b7f32f8d297929dd94af3d'),
 ObjectId('67b7f32f8d297929dd94af3e'),
 ObjectId('67b7f32f8d297929dd94af3f'),
 ObjectId('67b7f32f8d297929dd94af40'),
 ObjectId('67b7f32f8d297929dd94af41'),
 ObjectId('67b7f32f8d297929dd94af42'),
 ObjectId('67b7f32f8d297929dd94af43'),
 ObjectId('67b7f32f8d297929dd94af44'),
 ObjectId('67b7f32f8d297929dd94af45'),
 ObjectId('67b7f32f8d297929dd94af46'),
 ObjectId('67b7f32f8d297929dd94af47'),
 ObjectId('67b7f32f8d297929dd94af48'),
 ObjectId('67b7f32f8d297929dd94af49'),
 ObjectId('67b7f32f8d297929dd94af4a'),
 ObjectId('67b7f32f8d297929dd94af4b'),
 ObjectId('67b7f32f8d297929dd94af4c'),
 ObjectId('67b7f32f8d297929dd94af4d'),
 ObjectId('67b7f32f8d297929dd94af4e'),
 ObjectId('67b7f32f8d297929dd94af4f'),
 ObjectId('67b7f32f8d297929dd94af50'),
 ObjectId('67b7f32f8d297929dd94af51'),
 ObjectId('67b7f32f8d297929dd94af52'),
 ObjectId('67b7f32f8d297929dd94af53'),
 ObjectId('67b7f32f8d297929dd94af54'),
 ObjectId('67b7f32f8d297929dd94af55'),
 ObjectId('67b7f32f8d297929dd94af56'),
 ObjectId('67b7f32f8d297929dd94af57'),
 ObjectId('67b7f32f8d297929dd94af58'),
 ObjectId('67b7f32f8d297929dd94af59'),
 ObjectId('67b7f32f8d297929dd94af5a'),
 ObjectId('67b7f32f8d297929dd94af5b'),
 ObjectId('67b7f32f8d297929dd94af5c'),
 ObjectId('67b7f32f8d297929dd94af5d'),
 ObjectId('67b7f32f8d297929dd94af5e'),
 ObjectId('67b7f32f8d297929dd94af5f'),
 ObjectId('67b7f32f8d297929dd94af60'),
 ObjectId('67b7f32f8d297929dd94af61'),
 ObjectId('67b7f32f8d297929dd94af62'),
 ObjectId('67b7f32f8d297929dd94af63'),
 ObjectId('67b7f32f8d297929dd94af64'),
 ObjectId('67b7f32f8d297929dd94af65'),
 ObjectId('67b7f32f8d297929dd94af66'),
 ObjectId('67b7f32f8d297929dd94af67'),
 ObjectId('67b7f32f8d297929dd94af68'),
 ObjectId('67b7f32f8d297929dd94af69'),
 ObjectId('67b7f32f8d297929dd94af6a'),
 ObjectId('67b7f32f8d297929dd94af6b'),
 ObjectId('67b7f32f8d297929dd94af6c'),
 ObjectId('67b7f32f8d297929dd94af6d'),
 ObjectId('67b7f32f8d297929dd94af6e'),
 ObjectId('67b7f32f8d297929dd94af6f'),
 ObjectId('67b7f32f8d297929dd94af70'),
 ObjectId('67b7f32f8d297929dd94af71'),
 ObjectId('67b7f32f8d297929dd94af72'),
 ObjectId('67b7f32f8d297929dd94af73'),
 ObjectId('67b7f32f8d297929dd94af74'),
 ObjectId('67b7f32f8d297929dd94af75'),
 ObjectId('67b7f32f8d297929dd94af76'),
 ObjectId('67b7f32f8d297929dd94af77'),
 ObjectId('67b7f32f8d297929dd94af78'),
 ObjectId('67b7f32f8d297929dd94af79'),
 ObjectId('67b7f32f8d297929dd94af7a'),
 ObjectId('67b7f32f8d297929dd94af7b'),
 ObjectId('67b7f32f8d297929dd94af7c'),
 ObjectId('67b7f32f8d297929dd94af7d'),
 ObjectId('67b7f32f8d297929dd94af7e'),
 ObjectId('67b7f32f8d297929dd94af7f'),
 ObjectId('67b7f32f8d297929dd94af80'),
 ObjectId('67b7f32f8d297929dd94af81'),
 ObjectId('67b7f32f8d297929dd94af82'),
 ObjectId('67b7f32f8d297929dd94af83'),
 ObjectId('67b7f32f8d297929dd94af84'),
 ObjectId('67b7f32f8d297929dd94af85'),
 ObjectId('67b7f32f8d297929dd94af86'),
 ObjectId('67b7f32f8d297929dd94af87'),
 ObjectId('67b7f32f8d297929dd94af88'),
 ObjectId('67b7f32f8d297929dd94af89'),
 ObjectId('67b7f32f8d297929dd94af8a'),
 ObjectId('67b7f32f8d297929dd94af8b'),
 ObjectId('67b7f32f8d297929dd94af8c'),
 ObjectId('67b7f32f8d297929dd94af8d'),
 ObjectId('67b7f32f8d297929dd94af8e'),
 ObjectId('67b7f32f8d297929dd94af8f'),
 ObjectId('67b7f32f8d297929dd94af90'),
 ObjectId('67b7f32f8d297929dd94af91'),
 ObjectId('67b7f32f8d297929dd94af92'),
 ObjectId('67b7f32f8d297929dd94af93'),
 ObjectId('67b7f32f8d297929dd94af94'),
 ObjectId('67b7f32f8d297929dd94af95'),
 ObjectId('67b7f32f8d297929dd94af96'),
 ObjectId('67b7f32f8d297929dd94af97'),
 ObjectId('67b7f32f8d297929dd94af98'),
 ObjectId('67b7f32f8d297929dd94af99'),
 ObjectId('67b7f32f8d297929dd94af9a'),
 ObjectId('67b7f32f8d297929dd94af9b'),
 ObjectId('67b7f32f8d297929dd94af9c'),
 ObjectId('67b7f32f8d297929dd94af9d'),
 ObjectId('67b7f32f8d297929dd94af9e'),
 ObjectId('67b7f32f8d297929dd94af9f'),
 ObjectId('67b7f32f8d297929dd94afa0'),
 ObjectId('67b7f32f8d297929dd94afa1'),
 ObjectId('67b7f32f8d297929dd94afa2'),
 ObjectId('67b7f32f8d297929dd94afa3'),
 ObjectId('67b7f32f8d297929dd94afa4'),
 ObjectId('67b7f32f8d297929dd94afa5'),
 ObjectId('67b7f32f8d297929dd94afa6'),
 ObjectId('67b7f32f8d297929dd94afa7'),
 ObjectId('67b7f32f8d297929dd94afa8'),
 ObjectId('67b7f32f8d297929dd94afa9'),
 ObjectId('67b7f32f8d297929dd94afaa'),
 ObjectId('67b7f32f8d297929dd94afab'),
 ObjectId('67b7f32f8d297929dd94afac'),
 ObjectId('67b7f32f8d297929dd94afad'),
 ObjectId('67b7f32f8d297929dd94afae'),
 ObjectId('67b7f32f8d297929dd94afaf'),
 ObjectId('67b7f32f8d297929dd94afb0'),
 ObjectId('67b7f32f8d297929dd94afb1'),
 ObjectId('67b7f32f8d297929dd94afb2'),
 ObjectId('67b7f32f8d297929dd94afb3'),
 ObjectId('67b7f32f8d297929dd94afb4'),
 ObjectId('67b7f32f8d297929dd94afb5'),
 ObjectId('67b7f32f8d297929dd94afb6'),
 ObjectId('67b7f32f8d297929dd94afb7'),
 ObjectId('67b7f32f8d297929dd94afb8'),
 ObjectId('67b7f32f8d297929dd94afb9'),
 ObjectId('67b7f32f8d297929dd94afba'),
 ObjectId('67b7f32f8d297929dd94afbb'),
 ObjectId('67b7f32f8d297929dd94afbc'),
 ObjectId('67b7f32f8d297929dd94afbd'),
 ObjectId('67b7f32f8d297929dd94afbe'),
 ObjectId('67b7f32f8d297929dd94afbf'),
 ObjectId('67b7f32f8d297929dd94afc0'),
 ObjectId('67b7f32f8d297929dd94afc1'),
 ObjectId('67b7f32f8d297929dd94afc2'),
 ObjectId('67b7f32f8d297929dd94afc3'),
 ObjectId('67b7f32f8d297929dd94afc4'),
 ObjectId('67b7f32f8d297929dd94afc5'),
 ObjectId('67b7f32f8d297929dd94afc6'),
 ObjectId('67b7f32f8d297929dd94afc7'),
 ObjectId('67b7f32f8d297929dd94afc8'),
 ObjectId('67b7f32f8d297929dd94afc9'),
 ObjectId('67b7f32f8d297929dd94afca'),
 ObjectId('67b7f32f8d297929dd94afcb'),
 ObjectId('67b7f32f8d297929dd94afcc'),
 ObjectId('67b7f32f8d297929dd94afcd'),
 ObjectId('67b7f32f8d297929dd94afce'),
 ObjectId('67b7f32f8d297929dd94afcf'),
 ObjectId('67b7f32f8d297929dd94afd0'),
 ObjectId('67b7f32f8d297929dd94afd1'),
 ObjectId('67b7f32f8d297929dd94afd2'),
 ObjectId('67b7f32f8d297929dd94afd3'),
 ObjectId('67b7f32f8d297929dd94afd4'),
 ObjectId('67b7f32f8d297929dd94afd5'),
 ObjectId('67b7f32f8d297929dd94afd6'),
 ObjectId('67b7f32f8d297929dd94afd7'),
 ObjectId('67b7f32f8d297929dd94afd8'),
 ObjectId('67b7f32f8d297929dd94afd9'),
 ObjectId('67b7f32f8d297929dd94afda'),
 ObjectId('67b7f32f8d297929dd94afdb'),
 ObjectId('67b7f32f8d297929dd94afdc'),
 ObjectId('67b7f32f8d297929dd94afdd'),
 ObjectId('67b7f32f8d297929dd94afde'),
 ObjectId('67b7f32f8d297929dd94afdf'),
 ObjectId('67b7f32f8d297929dd94afe0'),
 ObjectId('67b7f32f8d297929dd94afe1'),
 ObjectId('67b7f32f8d297929dd94afe2'),
 ObjectId('67b7f32f8d297929dd94afe3'),
 ObjectId('67b7f32f8d297929dd94afe4'),
 ObjectId('67b7f32f8d297929dd94afe5'),
 ObjectId('67b7f32f8d297929dd94afe6'),
 ObjectId('67b7f32f8d297929dd94afe7'),
 ObjectId('67b7f32f8d297929dd94afe8'),
 ObjectId('67b7f32f8d297929dd94afe9'),
 ObjectId('67b7f32f8d297929dd94afea'),
 ObjectId('67b7f32f8d297929dd94afeb'),
 ObjectId('67b7f32f8d297929dd94afec'),
 ObjectId('67b7f32f8d297929dd94afed'),
 ObjectId('67b7f32f8d297929dd94afee'),
 ObjectId('67b7f32f8d297929dd94afef'),
 ObjectId('67b7f32f8d297929dd94aff0'),
 ObjectId('67b7f32f8d297929dd94aff1'),
 ObjectId('67b7f32f8d297929dd94aff2'),
 ObjectId('67b7f32f8d297929dd94aff3'),
 ObjectId('67b7f32f8d297929dd94aff4'),
 ObjectId('67b7f32f8d297929dd94aff5'),
 ObjectId('67b7f32f8d297929dd94aff6'),
 ObjectId('67b7f32f8d297929dd94aff7'),
 ObjectId('67b7f32f8d297929dd94aff8'),
 ObjectId('67b7f32f8d297929dd94aff9'),
 ObjectId('67b7f32f8d297929dd94affa'),
 ObjectId('67b7f32f8d297929dd94affb'),
 ObjectId('67b7f32f8d297929dd94affc'),
 ObjectId('67b7f32f8d297929dd94affd'),
 ObjectId('67b7f32f8d297929dd94affe'),
 ObjectId('67b7f32f8d297929dd94afff'),
 ObjectId('67b7f32f8d297929dd94b000'),
 ObjectId('67b7f32f8d297929dd94b001'),
 ObjectId('67b7f32f8d297929dd94b002'),
 ObjectId('67b7f32f8d297929dd94b003'),
 ObjectId('67b7f32f8d297929dd94b004'),
 ObjectId('67b7f32f8d297929dd94b005'),
 ObjectId('67b7f32f8d297929dd94b006'),
 ObjectId('67b7f32f8d297929dd94b007'),
 ObjectId('67b7f32f8d297929dd94b008'),
 ObjectId('67b7f32f8d297929dd94b009'),
 ObjectId('67b7f32f8d297929dd94b00a'),
 ObjectId('67b7f32f8d297929dd94b00b'),
 ObjectId('67b7f32f8d297929dd94b00c'),
 ObjectId('67b7f32f8d297929dd94b00d'),
 ObjectId('67b7f32f8d297929dd94b00e'),
 ObjectId('67b7f32f8d297929dd94b00f'),
 ObjectId('67b7f32f8d297929dd94b010'),
 ObjectId('67b7f32f8d297929dd94b011'),
 ObjectId('67b7f32f8d297929dd94b012'),
 ObjectId('67b7f32f8d297929dd94b013'),
 ObjectId('67b7f32f8d297929dd94b014'),
 ObjectId('67b7f32f8d297929dd94b015'),
 ObjectId('67b7f32f8d297929dd94b016'),
 ObjectId('67b7f32f8d297929dd94b017'),
 ObjectId('67b7f32f8d297929dd94b018'),
 ObjectId('67b7f32f8d297929dd94b019'),
 ObjectId('67b7f32f8d297929dd94b01a'),
 ObjectId('67b7f32f8d297929dd94b01b'),
 ObjectId('67b7f32f8d297929dd94b01c'),
 ObjectId('67b7f32f8d297929dd94b01d'),
 ObjectId('67b7f32f8d297929dd94b01e'),
 ObjectId('67b7f32f8d297929dd94b01f'),
 ObjectId('67b7f32f8d297929dd94b020'),
 ObjectId('67b7f32f8d297929dd94b021'),
 ObjectId('67b7f32f8d297929dd94b022'),
 ObjectId('67b7f32f8d297929dd94b023'),
 ObjectId('67b7f32f8d297929dd94b024'),
 ObjectId('67b7f32f8d297929dd94b025'),
 ObjectId('67b7f32f8d297929dd94b026'),
 ObjectId('67b7f32f8d297929dd94b027'),
 ObjectId('67b7f32f8d297929dd94b028'),
 ObjectId('67b7f32f8d297929dd94b029'),
 ObjectId('67b7f32f8d297929dd94b02a'),
 ObjectId('67b7f32f8d297929dd94b02b'),
 ObjectId('67b7f32f8d297929dd94b02c'),
 ObjectId('67b7f32f8d297929dd94b02d'),
 ObjectId('67b7f32f8d297929dd94b02e'),
 ObjectId('67b7f32f8d297929dd94b02f'),
 ObjectId('67b7f32f8d297929dd94b030'),
 ObjectId('67b7f32f8d297929dd94b031'),
 ObjectId('67b7f32f8d297929dd94b032'),
 ObjectId('67b7f32f8d297929dd94b033'),
 ObjectId('67b7f32f8d297929dd94b034'),
 ObjectId('67b7f32f8d297929dd94b035'),
 ObjectId('67b7f32f8d297929dd94b036'),
 ObjectId('67b7f32f8d297929dd94b037'),
 ObjectId('67b7f32f8d297929dd94b038'),
 ObjectId('67b7f32f8d297929dd94b039'),
 ObjectId('67b7f32f8d297929dd94b03a'),
 ObjectId('67b7f32f8d297929dd94b03b'),
 ObjectId('67b7f32f8d297929dd94b03c'),
 ObjectId('67b7f32f8d297929dd94b03d'),
 ObjectId('67b7f32f8d297929dd94b03e'),
 ObjectId('67b7f32f8d297929dd94b03f'),
 ObjectId('67b7f32f8d297929dd94b040'),
 ObjectId('67b7f32f8d297929dd94b041'),
 ObjectId('67b7f32f8d297929dd94b042'),
 ObjectId('67b7f32f8d297929dd94b043'),
 ObjectId('67b7f32f8d297929dd94b044'),
 ObjectId('67b7f32f8d297929dd94b045'),
 ObjectId('67b7f32f8d297929dd94b046'),
 ObjectId('67b7f32f8d297929dd94b047'),
 ObjectId('67b7f32f8d297929dd94b048'),
 ObjectId('67b7f32f8d297929dd94b049'),
 ObjectId('67b7f32f8d297929dd94b04a'),
 ObjectId('67b7f32f8d297929dd94b04b'),
 ObjectId('67b7f32f8d297929dd94b04c'),
 ObjectId('67b7f32f8d297929dd94b04d'),
 ObjectId('67b7f32f8d297929dd94b04e'),
 ObjectId('67b7f32f8d297929dd94b04f'),
 ObjectId('67b7f32f8d297929dd94b050'),
 ObjectId('67b7f32f8d297929dd94b051'),
 ObjectId('67b7f32f8d297929dd94b052'),
 ObjectId('67b7f32f8d297929dd94b053'),
 ObjectId('67b7f32f8d297929dd94b054'),
 ObjectId('67b7f32f8d297929dd94b055'),
 ObjectId('67b7f32f8d297929dd94b056'),
 ObjectId('67b7f32f8d297929dd94b057'),
 ObjectId('67b7f32f8d297929dd94b058'),
 ObjectId('67b7f32f8d297929dd94b059'),
 ObjectId('67b7f32f8d297929dd94b05a'),
 ObjectId('67b7f32f8d297929dd94b05b'),
 ObjectId('67b7f32f8d297929dd94b05c'),
 ObjectId('67b7f32f8d297929dd94b05d'),
 ObjectId('67b7f32f8d297929dd94b05e'),
 ObjectId('67b7f32f8d297929dd94b05f'),
 ObjectId('67b7f32f8d297929dd94b060'),
 ObjectId('67b7f32f8d297929dd94b061'),
 ObjectId('67b7f32f8d297929dd94b062'),
 ObjectId('67b7f32f8d297929dd94b063'),
 ObjectId('67b7f32f8d297929dd94b064'),
 ObjectId('67b7f32f8d297929dd94b065'),
 ObjectId('67b7f32f8d297929dd94b066'),
 ObjectId('67b7f32f8d297929dd94b067'),
 ObjectId('67b7f32f8d297929dd94b068'),
 ObjectId('67b7f32f8d297929dd94b069'),
 ObjectId('67b7f32f8d297929dd94b06a'),
 ObjectId('67b7f32f8d297929dd94b06b'),
 ObjectId('67b7f32f8d297929dd94b06c'),
 ObjectId('67b7f32f8d297929dd94b06d'),
 ObjectId('67b7f32f8d297929dd94b06e'),
 ObjectId('67b7f32f8d297929dd94b06f'),
 ObjectId('67b7f32f8d297929dd94b070'),
 ObjectId('67b7f32f8d297929dd94b071'),
 ObjectId('67b7f32f8d297929dd94b072'),
 ObjectId('67b7f32f8d297929dd94b073'),
 ObjectId('67b7f32f8d297929dd94b074'),
 ObjectId('67b7f32f8d297929dd94b075'),
 ObjectId('67b7f32f8d297929dd94b076'),
 ObjectId('67b7f32f8d297929dd94b077'),
 ObjectId('67b7f32f8d297929dd94b078'),
 ObjectId('67b7f32f8d297929dd94b079'),
 ObjectId('67b7f32f8d297929dd94b07a'),
 ObjectId('67b7f32f8d297929dd94b07b'),
 ObjectId('67b7f32f8d297929dd94b07c'),
 ObjectId('67b7f32f8d297929dd94b07d'),
 ObjectId('67b7f32f8d297929dd94b07e'),
 ObjectId('67b7f32f8d297929dd94b07f'),
 ObjectId('67b7f32f8d297929dd94b080'),
 ObjectId('67b7f32f8d297929dd94b081'),
 ObjectId('67b7f32f8d297929dd94b082'),
 ObjectId('67b7f32f8d297929dd94b083'),
 ObjectId('67b7f32f8d297929dd94b084'),
 ObjectId('67b7f32f8d297929dd94b085'),
 ObjectId('67b7f32f8d297929dd94b086'),
 ObjectId('67b7f32f8d297929dd94b087'),
 ObjectId('67b7f32f8d297929dd94b088'),
 ObjectId('67b7f32f8d297929dd94b089'),
 ObjectId('67b7f32f8d297929dd94b08a'),
 ObjectId('67b7f32f8d297929dd94b08b'),
 ObjectId('67b7f32f8d297929dd94b08c'),
 ObjectId('67b7f32f8d297929dd94b08d'),
 ObjectId('67b7f32f8d297929dd94b08e'),
 ObjectId('67b7f32f8d297929dd94b08f'),
 ObjectId('67b7f32f8d297929dd94b090'),
 ObjectId('67b7f32f8d297929dd94b091'),
 ObjectId('67b7f32f8d297929dd94b092'),
 ObjectId('67b7f32f8d297929dd94b093'),
 ObjectId('67b7f32f8d297929dd94b094'),
 ObjectId('67b7f32f8d297929dd94b095'),
 ObjectId('67b7f32f8d297929dd94b096'),
 ObjectId('67b7f32f8d297929dd94b097'),
 ObjectId('67b7f32f8d297929dd94b098'),
 ObjectId('67b7f32f8d297929dd94b099'),
 ObjectId('67b7f32f8d297929dd94b09a'),
 ObjectId('67b7f32f8d297929dd94b09b'),
 ObjectId('67b7f32f8d297929dd94b09c'),
 ObjectId('67b7f32f8d297929dd94b09d'),
 ObjectId('67b7f32f8d297929dd94b09e'),
 ObjectId('67b7f32f8d297929dd94b09f'),
 ObjectId('67b7f32f8d297929dd94b0a0'),
 ObjectId('67b7f32f8d297929dd94b0a1'),
 ObjectId('67b7f32f8d297929dd94b0a2'),
 ObjectId('67b7f32f8d297929dd94b0a3'),
 ObjectId('67b7f32f8d297929dd94b0a4'),
 ObjectId('67b7f32f8d297929dd94b0a5'),
 ObjectId('67b7f32f8d297929dd94b0a6'),
 ObjectId('67b7f32f8d297929dd94b0a7'),
 ObjectId('67b7f32f8d297929dd94b0a8'),
 ObjectId('67b7f32f8d297929dd94b0a9'),
 ObjectId('67b7f32f8d297929dd94b0aa'),
 ObjectId('67b7f32f8d297929dd94b0ab'),
 ObjectId('67b7f32f8d297929dd94b0ac'),
 ObjectId('67b7f32f8d297929dd94b0ad'),
 ObjectId('67b7f32f8d297929dd94b0ae'),
 ObjectId('67b7f32f8d297929dd94b0af'),
 ObjectId('67b7f32f8d297929dd94b0b0'),
 ObjectId('67b7f32f8d297929dd94b0b1'),
 ObjectId('67b7f32f8d297929dd94b0b2'),
 ObjectId('67b7f32f8d297929dd94b0b3'),
 ObjectId('67b7f32f8d297929dd94b0b4'),
 ObjectId('67b7f32f8d297929dd94b0b5'),
 ObjectId('67b7f32f8d297929dd94b0b6'),
 ObjectId('67b7f32f8d297929dd94b0b7'),
 ObjectId('67b7f32f8d297929dd94b0b8'),
 ObjectId('67b7f32f8d297929dd94b0b9'),
 ObjectId('67b7f32f8d297929dd94b0ba'),
 ObjectId('67b7f32f8d297929dd94b0bb'),
 ObjectId('67b7f32f8d297929dd94b0bc'),
 ObjectId('67b7f32f8d297929dd94b0bd'),
 ObjectId('67b7f32f8d297929dd94b0be'),
 ObjectId('67b7f32f8d297929dd94b0bf'),
 ObjectId('67b7f32f8d297929dd94b0c0'),
 ObjectId('67b7f32f8d297929dd94b0c1'),
 ObjectId('67b7f32f8d297929dd94b0c2'),
 ObjectId('67b7f32f8d297929dd94b0c3'),
 ObjectId('67b7f32f8d297929dd94b0c4'),
 ObjectId('67b7f32f8d297929dd94b0c5'),
 ObjectId('67b7f32f8d297929dd94b0c6'),
 ObjectId('67b7f32f8d297929dd94b0c7'),
 ObjectId('67b7f32f8d297929dd94b0c8'),
 ObjectId('67b7f32f8d297929dd94b0c9'),
 ObjectId('67b7f32f8d297929dd94b0ca'),
 ObjectId('67b7f32f8d297929dd94b0cb'),
 ObjectId('67b7f32f8d297929dd94b0cc'),
 ObjectId('67b7f32f8d297929dd94b0cd'),
 ObjectId('67b7f32f8d297929dd94b0ce'),
 ObjectId('67b7f32f8d297929dd94b0cf'),
 ObjectId('67b7f32f8d297929dd94b0d0'),
 ObjectId('67b7f32f8d297929dd94b0d1'),
 ObjectId('67b7f32f8d297929dd94b0d2'),
 ObjectId('67b7f32f8d297929dd94b0d3'),
 ObjectId('67b7f32f8d297929dd94b0d4'),
 ObjectId('67b7f32f8d297929dd94b0d5'),
 ObjectId('67b7f32f8d297929dd94b0d6'),
 ObjectId('67b7f32f8d297929dd94b0d7'),
 ObjectId('67b7f32f8d297929dd94b0d8'),
 ObjectId('67b7f32f8d297929dd94b0d9'),
 ObjectId('67b7f32f8d297929dd94b0da'),
 ObjectId('67b7f32f8d297929dd94b0db'),
 ObjectId('67b7f32f8d297929dd94b0dc'),
 ObjectId('67b7f32f8d297929dd94b0dd'),
 ObjectId('67b7f32f8d297929dd94b0de'),
 ObjectId('67b7f32f8d297929dd94b0df'),
 ObjectId('67b7f32f8d297929dd94b0e0'),

In [62]:
records = df.to_dict(orient='records')
records

[{'concept': 'NumberOfSubmissionDEI',
  'concept_jp': '提出回数',
  'value': '1',
  'unit': 'pure',
  'context': 'FilingDateInstant',
  'context_YYYY': None,
  'context_NCM': False},
 {'concept': 'OrdinaryIncomeSummaryOfBusinessResults',
  'concept_jp': '経常収益',
  'value': '88871000000',
  'unit': 'JPY',
  'context': 'Prior4YearDuration',
  'context_YYYY': '2020',
  'context_NCM': False},
 {'concept': 'OrdinaryIncomeSummaryOfBusinessResults',
  'concept_jp': '経常収益',
  'value': '85715000000',
  'unit': 'JPY',
  'context': 'Prior3YearDuration',
  'context_YYYY': '2021',
  'context_NCM': False},
 {'concept': 'OrdinaryIncomeSummaryOfBusinessResults',
  'concept_jp': '経常収益',
  'value': '98306000000',
  'unit': 'JPY',
  'context': 'Prior2YearDuration',
  'context_YYYY': '2022',
  'context_NCM': False},
 {'concept': 'OrdinaryIncomeSummaryOfBusinessResults',
  'concept_jp': '経常収益',
  'value': '115289000000',
  'unit': 'JPY',
  'context': 'Prior1YearDuration',
  'context_YYYY': '2023',
  'context_NCM': False},
 {'concept': 'OrdinaryIncomeSummaryOfBusinessResults',
  'concept_jp': '経常収益',
  'value': '122630000000',
  'unit': 'JPY',
  'context': 'CurrentYearDuration',
  'context_YYYY': '2024',
  'context_NCM': False},
 {'concept': 'TrustFeesSummaryOfBusinessResults',
  'concept_jp': '信託報酬',
  'value': '',
  'unit': 'JPY',
  'context': 'Prior4YearDuration',
  'context_YYYY': '2020',
  'context_NCM': False},
 {'concept': 'TrustFeesSummaryOfBusinessResults',
  'concept_jp': '信託報酬',
  'value': '2000000',
  'unit': 'JPY',
  'context': 'Prior3YearDuration',
  'context_YYYY': '2021',
  'context_NCM': False},
 {'concept': 'TrustFeesSummaryOfBusinessResults',
  'concept_jp': '信託報酬',
  'value': '0',
  'unit': 'JPY',
  'context': 'Prior2YearDuration',
  'context_YYYY': '2022',
  'context_NCM': False},
 {'concept': 'TrustFeesSummaryOfBusinessResults',
  'concept_jp': '信託報酬',
  'value': '0',
  'unit': 'JPY',
  'context': 'Prior1YearDuration',
  'context_YYYY': '2023',
  'context_NCM': False},
 {'concept': 'TrustFeesSummaryOfBusinessResults',
  'concept_jp': '信託報酬',
  'value': '0',
  'unit': 'JPY',
  'context': 'CurrentYearDuration',
  'context_YYYY': '2024',
  'context_NCM': False},
 {'concept': 'OrdinaryIncomeLossSummaryOfBusinessResults',
  'concept_jp': '経常利益又は経常損失（△）',
  'value': '13875000000',
  'unit': 'JPY',
  'context': 'Prior4YearDuration',
  'context_YYYY': '2020',
  'context_NCM': False},
 {'concept': 'OrdinaryIncomeLossSummaryOfBusinessResults',
  'concept_jp': '経常利益又は経常損失（△）',
  'value': '11070000000',
  'unit': 'JPY',
  'context': 'Prior3YearDuration',
  'context_YYYY': '2021',
  'context_NCM': False},
 {'concept': 'OrdinaryIncomeLossSummaryOfBusinessResults',
  'concept_jp': '経常利益又は経常損失（△）',
  'value': '23999000000',
  'unit': 'JPY',
  'context': 'Prior2YearDuration',
  'context_YYYY': '2022',
  'context_NCM': False},
 {'concept': 'OrdinaryIncomeLossSummaryOfBusinessResults',
  'concept_jp': '経常利益又は経常損失（△）',
  'value': '20041000000',
  'unit': 'JPY',
  'context': 'Prior1YearDuration',
  'context_YYYY': '2023',
  'context_NCM': False},
 {'concept': 'OrdinaryIncomeLossSummaryOfBusinessResults',
  'concept_jp': '経常利益又は経常損失（△）',
  'value': '23967000000',
  'unit': 'JPY',
  'context': 'CurrentYearDuration',
  'context_YYYY': '2024',
  'context_NCM': False},
 {'concept': 'ProfitLossAttributableToOwnersOfParentSummaryOfBusinessResults',
  'concept_jp': '親会社株主に帰属する当期純利益又は親会社株主に帰属する当期純損失（△）',
  'value': '12412000000',
  'unit': 'JPY',
  'context': 'Prior4YearDuration',
  'context_YYYY': '2020',
  'context_NCM': False},
 {'concept': 'ProfitLossAttributableToOwnersOfParentSummaryOfBusinessResults',
  'concept_jp': '親会社株主に帰属する当期純利益又は親会社株主に帰属する当期純損失（△）',
  'value': '11448000000',
  'unit': 'JPY',
  'context': 'Prior3YearDuration',
  'context_YYYY': '2021',
  'context_NCM': False},
 {'concept': 'ProfitLossAttributableToOwnersOfParentSummaryOfBusinessResults',
  'concept_jp': '親会社株主に帰属する当期純利益又は親会社株主に帰属する当期純損失（△）',
  'value': '17715000000',
  'unit': 'JPY',
  'context': 'Prior2YearDuration',
  'context_YYYY': '2022',
  'context_NCM': False},
 {'concept': 'ProfitLossAttributableToOwnersOfParentSummaryOfBusinessResults',
  'concept_jp': '親会社株主に帰属する当期純利益又は親会社株主に帰属する当期純損失（△）',
  'value': '14858000000',
  'unit': 'JPY',
  'context': 'Prior1YearDuration',
  'context_YYYY': '2023',
  'context_NCM': False},
 {'concept': 'ProfitLossAttributableToOwnersOfParentSummaryOfBusinessResults',
  'concept_jp': '親会社株主に帰属する当期純利益又は親会社株主に帰属する当期純損失（△）',
  'value': '15940000000',
  'unit': 'JPY',
  'context': 'CurrentYearDuration',
  'context_YYYY': '2024',
  'context_NCM': False},
 {'concept': 'ComprehensiveIncomeSummaryOfBusinessResults',
  'concept_jp': '包括利益',
  'value': '-22117000000',
  'unit': 'JPY',
  'context': 'Prior4YearDuration',
  'context_YYYY': '2020',
  'context_NCM': False},
 {'concept': 'ComprehensiveIncomeSummaryOfBusinessResults',
  'concept_jp': '包括利益',
  'value': '122660000000',
  'unit': 'JPY',
  'context': 'Prior3YearDuration',
  'context_YYYY': '2021',
  'context_NCM': False},
 {'concept': 'ComprehensiveIncomeSummaryOfBusinessResults',
  'concept_jp': '包括利益',
  'value': '-26692000000',
  'unit': 'JPY',
  'context': 'Prior2YearDuration',
  'context_YYYY': '2022',
  'context_NCM': False},
 {'concept': 'ComprehensiveIncomeSummaryOfBusinessResults',
  'concept_jp': '包括利益',
  'value': '-15071000000',
  'unit': 'JPY',
  'context': 'Prior1YearDuration',
  'context_YYYY': '2023',
  'context_NCM': False},
 {'concept': 'ComprehensiveIncomeSummaryOfBusinessResults',
  'concept_jp': '包括利益',
  'value': '55925000000',
  'unit': 'JPY',
  'context': 'CurrentYearDuration',
  'context_YYYY': '2024',
  'context_NCM': False},
 {'concept': 'NetAssetsSummaryOfBusinessResults',
  'concept_jp': '純資産額',
  'value': '375801000000',
  'unit': 'JPY',
  'context': 'Prior4YearInstant',
  'context_YYYY': '2020',
  'context_NCM': False},
 {'concept': 'NetAssetsSummaryOfBusinessResults',
  'concept_jp': '純資産額',
  'value': '495469000000',
  'unit': 'JPY',
  'context': 'Prior3YearInstant',
  'context_YYYY': '2021',
  'context_NCM': False},
 {'concept': 'NetAssetsSummaryOfBusinessResults',
  'concept_jp': '純資産額',
  'value': '464214000000',
  'unit': 'JPY',
  'context': 'Prior2YearInstant',
  'context_YYYY': '2022',
  'context_NCM': False},
 {'concept': 'NetAssetsSummaryOfBusinessResults',
  'concept_jp': '純資産額',
  'value': '441222000000',
  'unit': 'JPY',
  'context': 'Prior1YearInstant',
  'context_YYYY': '2023',
  'context_NCM': False},
 {'concept': 'NetAssetsSummaryOfBusinessResults',
  'concept_jp': '純資産額',
  'value': '490887000000',
  'unit': 'JPY',
  'context': 'CurrentYearInstant',
  'context_YYYY': '2024',
  'context_NCM': False},
 {'concept': 'TotalAssetsSummaryOfBusinessResults',
  'concept_jp': '総資産額',
  'value': '6285002000000',
  'unit': 'JPY',
  'context': 'Prior4YearInstant',
  'context_YYYY': '2020',
  'context_NCM': False},
 {'concept': 'TotalAssetsSummaryOfBusinessResults',
  'concept_jp': '総資産額',
  'value': '7793748000000',
  'unit': 'JPY',
  'context': 'Prior3YearInstant',
  'context_YYYY': '2021',
  'context_NCM': False},
 {'concept': 'TotalAssetsSummaryOfBusinessResults',
  'concept_jp': '総資産額',
  'value': '7537956000000',
  'unit': 'JPY',
  'context': 'Prior2YearInstant',
  'context_YYYY': '2022',
  'context_NCM': False},
 {'concept': 'TotalAssetsSummaryOfBusinessResults',
  'concept_jp': '総資産額',
  'value': '7305698000000',
  'unit': 'JPY',
  'context': 'Prior1YearInstant',
  'context_YYYY': '2023',
  'context_NCM': False},
 {'concept': 'TotalAssetsSummaryOfBusinessResults',
  'concept_jp': '総資産額',
  'value': '7970551000000',
  'unit': 'JPY',
  'context': 'CurrentYearInstant',
  'context_YYYY': '2024',
  'context_NCM': False},
 {'concept': 'NetAssetsPerShareSummaryOfBusinessResults',
  'concept_jp': '１株当たり純資産額',
  'value': '7482.34',
  'unit': 'JPYPerShares',
  'context': 'Prior4YearInstant',
  'context_YYYY': '2020',
  'context_NCM': False},
 {'concept': 'NetAssetsPerShareSummaryOfBusinessResults',
  'concept_jp': '１株当たり純資産額',
  'value': '9958.46',
  'unit': 'JPYPerShares',
  'context': 'Prior3YearInstant',
  'context_YYYY': '2021',
  'context_NCM': False},
 {'concept': 'NetAssetsPerShareSummaryOfBusinessResults',
  'concept_jp': '１株当たり純資産額',
  'value': '9552.14',
  'unit': 'JPYPerShares',
  'context': 'Prior2YearInstant',
  'context_YYYY': '2022',
  'context_NCM': False},
 {'concept': 'NetAssetsPerShareSummaryOfBusinessResults',
  'concept_jp': '１株当たり純資産額',
  'value': '9293.39',
  'unit': 'JPYPerShares',
  'context': 'Prior1YearInstant',
  'context_YYYY': '2023',
  'context_NCM': False},
 {'concept': 'NetAssetsPerShareSummaryOfBusinessResults',
  'concept_jp': '１株当たり純資産額',
  'value': '10459.88',
  'unit': 'JPYPerShares',
  'context': 'CurrentYearInstant',
  'context_YYYY': '2024',
  'context_NCM': False},
 {'concept': 'BasicEarningsLossPerShareSummaryOfBusinessResults',
  'concept_jp': '１株当たり当期純利益又は当期純損失（△）',
  'value': '243.05',
  'unit': 'JPYPerShares',
  'context': 'Prior4YearDuration',
  'context_YYYY': '2020',
  'context_NCM': False},
 {'concept': 'BasicEarningsLossPerShareSummaryOfBusinessResults',
  'concept_jp': '１株当たり当期純利益又は当期純損失（△）',
  'value': '228.12',
  'unit': 'JPYPerShares',
  'context': 'Prior3YearDuration',
  'context_YYYY': '2021',
  'context_NCM': False},
 {'concept': 'BasicEarningsLossPerShareSummaryOfBusinessResults',
  'concept_jp': '１株当たり当期純利益又は当期純損失（△）',
  'value': '359.50',
  'unit': 'JPYPerShares',
  'context': 'Prior2YearDuration',
  'context_YYYY': '2022',
  'context_NCM': False},
 {'concept': 'BasicEarningsLossPerShareSummaryOfBusinessResults',
  'concept_jp': '１株当たり当期純利益又は当期純損失（△）',
  'value': '310.57',
  'unit': 'JPYPerShares',
  'context': 'Prior1YearDuration',
  'context_YYYY': '2023',
  'context_NCM': False},
 {'concept': 'BasicEarningsLossPerShareSummaryOfBusinessResults',
  'concept_jp': '１株当たり当期純利益又は当期純損失（△）',
  'value': '336.31',
  'unit': 'JPYPerShares',
  'context': 'CurrentYearDuration',
  'context_YYYY': '2024',
  'context_NCM': False},
 {'concept': 'DilutedEarningsPerShareSummaryOfBusinessResults',
  'concept_jp': '潜在株式調整後１株当たり当期純利益',
  'value': '214.19',
  'unit': 'JPYPerShares',
  'context': 'Prior4YearDuration',
  'context_YYYY': '2020',
  'context_NCM': False},
 {'concept': 'DilutedEarningsPerShareSummaryOfBusinessResults',
  'concept_jp': '潜在株式調整後１株当たり当期純利益',
  'value': '220.43',
  'unit': 'JPYPerShares',
  'context': 'Prior3YearDuration',
  'context_YYYY': '2021',
  'context_NCM': False},
 {'concept': 'DilutedEarningsPerShareSummaryOfBusinessResults',
  'concept_jp': '潜在株式調整後１株当たり当期純利益',
  'value': '359.20',
  'unit': 'JPYPerShares',
  'context': 'Prior2YearDuration',
  'context_YYYY': '2022',
  'context_NCM': False},
 {'concept': 'DilutedEarningsPerShareSummaryOfBusinessResults',
  'concept_jp': '潜在株式調整後１株当たり当期純利益',
  'value': '310.49',
  'unit': 'JPYPerShares',
  'context': 'Prior1YearDuration',
  'context_YYYY': '2023',
  'context_NCM': False},
 {'concept': 'DilutedEarningsPerShareSummaryOfBusinessResults',
  'concept_jp': '潜在株式調整後１株当たり当期純利益',
  'value': '',
  'unit': 'JPYPerShares',
  'context': 'CurrentYearDuration',
  'context_YYYY': '2024',
  'context_NCM': False},
 {'concept': 'EquityToAssetRatioSummaryOfBusinessResults',
  'concept_jp': '自己資本比率',
  'value': '0.0597',
  'unit': 'pure',
  'context': 'Prior4YearInstant',
  'context_YYYY': '2020',
  'context_NCM': False},
 {'concept': 'EquityToAssetRatioSummaryOfBusinessResults',
  'concept_jp': '自己資本比率',
  'value': '0.0635',
  'unit': 'pure',
  'context': 'Prior3YearInstant',
  'context_YYYY': '2021',
  'context_NCM': False},
 {'concept': 'EquityToAssetRatioSummaryOfBusinessResults',
  'concept_jp': '自己資本比率',
  'value': '0.0615',
  'unit': 'pure',
  'context': 'Prior2YearInstant',
  'context_YYYY': '2022',
  'context_NCM': False},
 {'concept': 'EquityToAssetRatioSummaryOfBusinessResults',
  'concept_jp': '自己資本比率',
  'value': '0.0603',
  'unit': 'pure',
  'context': 'Prior1YearInstant',
  'context_YYYY': '2023',
  'context_NCM': False},
 {'concept': 'EquityToAssetRatioSummaryOfBusinessResults',
  'concept_jp': '自己資本比率',
  'value': '0.0615',
  'unit': 'pure',
  'context': 'CurrentYearInstant',
  'context_YYYY': '2024',
  'context_NCM': False},
 {'concept': 'RateOfReturnOnEquitySummaryOfBusinessResults',
  'concept_jp': '自己資本利益率',
  'value': '0.0319',
  'unit': 'pure',
  'context': 'Prior4YearDuration',
  'context_YYYY': '2020',
  'context_NCM': False},
 {'concept': 'RateOfReturnOnEquitySummaryOfBusinessResults',
  'concept_jp': '自己資本利益率',
  'value': '0.0262',
  'unit': 'pure',
  'context': 'Prior3YearDuration',
  'context_YYYY': '2021',
  'context_NCM': False},
 {'concept': 'RateOfReturnOnEquitySummaryOfBusinessResults',
  'concept_jp': '自己資本利益率',
  'value': '0.0369',
  'unit': 'pure',
  'context': 'Prior2YearDuration',
  'context_YYYY': '2022',
  'context_NCM': False},
 {'concept': 'RateOfReturnOnEquitySummaryOfBusinessResults',
  'concept_jp': '自己資本利益率',
  'value': '0.0328',
  'unit': 'pure',
  'context': 'Prior1YearDuration',
  'context_YYYY': '2023',
  'context_NCM': False},
 {'concept': 'RateOfReturnOnEquitySummaryOfBusinessResults',
  'concept_jp': '自己資本利益率',
  'value': '0.0342',
  'unit': 'pure',
  'context': 'CurrentYearDuration',
  'context_YYYY': '2024',
  'context_NCM': False},
 {'concept': 'PriceEarningsRatioSummaryOfBusinessResults',
  'concept_jp': '株価収益率',
  'value': '10.56',
  'unit': 'pure',
  'context': 'Prior4YearDuration',
  'context_YYYY': '2020',
  'context_NCM': False},
 {'concept': 'PriceEarningsRatioSummaryOfBusinessResults',
  'concept_jp': '株価収益率',
  'value': '10.50',
  'unit': 'pure',
  'context': 'Prior3YearDuration',
  'context_YYYY': '2021',
  'context_NCM': False},
 {'concept': 'PriceEarningsRatioSummaryOfBusinessResults',
  'concept_jp': '株価収益率',
  'value': '6.15',
  'unit': 'pure',
  'context': 'Prior2YearDuration',
  'context_YYYY': '2022',
  'context_NCM': False},
 {'concept': 'PriceEarningsRatioSummaryOfBusinessResults',
  'concept_jp': '株価収益率',
  'value': '8.62',
  'unit': 'pure',
  'context': 'Prior1YearDuration',
  'context_YYYY': '2023',
  'context_NCM': False},
 {'concept': 'PriceEarningsRatioSummaryOfBusinessResults',
  'concept_jp': '株価収益率',
  'value': '12.47',
  'unit': 'pure',
  'context': 'CurrentYearDuration',
  'context_YYYY': '2024',
  'context_NCM': False},
 {'concept': 'NetCashProvidedByUsedInOperatingActivitiesSummaryOfBusinessResults',
  'concept_jp': '営業活動によるキャッシュ・フロー',
  'value': '131260000000',
  'unit': 'JPY',
  'context': 'Prior4YearDuration',
  'context_YYYY': '2020',
  'context_NCM': False},
 {'concept': 'NetCashProvidedByUsedInOperatingActivitiesSummaryOfBusinessResults',
  'concept_jp': '営業活動によるキャッシュ・フロー',
  'value': '1240417000000',
  'unit': 'JPY',
  'context': 'Prior3YearDuration',
  'context_YYYY': '2021',
  'context_NCM': False},
 {'concept': 'NetCashProvidedByUsedInOperatingActivitiesSummaryOfBusinessResults',
  'concept_jp': '営業活動によるキャッシュ・フロー',
  'value': '-278958000000',
  'unit': 'JPY',
  'context': 'Prior2YearDuration',
  'context_YYYY': '2022',
  'context_NCM': False},
 {'concept': 'NetCashProvidedByUsedInOperatingActivitiesSummaryOfBusinessResults',
  'concept_jp': '営業活動によるキャッシュ・フロー',
  'value': '-483433000000',
  'unit': 'JPY',
  'context': 'Prior1YearDuration',
  'context_YYYY': '2023',
  'context_NCM': False},
 {'concept': 'NetCashProvidedByUsedInOperatingActivitiesSummaryOfBusinessResults',
  'concept_jp': '営業活動によるキャッシュ・フロー',
  'value': '453292000000',
  'unit': 'JPY',
  'context': 'CurrentYearDuration',
  'context_YYYY': '2024',
  'context_NCM': False},
 {'concept': 'NetCashProvidedByUsedInInvestingActivitiesSummaryOfBusinessResults',
  'concept_jp': '投資活動によるキャッシュ・フロー',
  'value': '6726000000',
  'unit': 'JPY',
  'context': 'Prior4YearDuration',
  'context_YYYY': '2020',
  'context_NCM': False},
 {'concept': 'NetCashProvidedByUsedInInvestingActivitiesSummaryOfBusinessResults',
  'concept_jp': '投資活動によるキャッシュ・フロー',
  'value': '-127874000000',
  'unit': 'JPY',
  'context': 'Prior3YearDuration',
  'context_YYYY': '2021',
  'context_NCM': False},
 {'concept': 'NetCashProvidedByUsedInInvestingActivitiesSummaryOfBusinessResults',
  'concept_jp': '投資活動によるキャッシュ・フロー',
  'value': '21823000000',
  'unit': 'JPY',
  'context': 'Prior2YearDuration',
  'context_YYYY': '2022',
  'context_NCM': False},
 {'concept': 'NetCashProvidedByUsedInInvestingActivitiesSummaryOfBusinessResults',
  'concept_jp': '投資活動によるキャッシュ・フロー',
  'value': '-57989000000',
  'unit': 'JPY',
  'context': 'Prior1YearDuration',
  'context_YYYY': '2023',
  'context_NCM': False},
 {'concept': 'NetCashProvidedByUsedInInvestingActivitiesSummaryOfBusinessResults',
  'concept_jp': '投資活動によるキャッシュ・フロー',
  'value': '-288586000000',
  'unit': 'JPY',
  'context': 'CurrentYearDuration',
  'context_YYYY': '2024',
  'context_NCM': False},
 {'concept': 'NetCashProvidedByUsedInFinancingActivitiesSummaryOfBusinessResults',
  'concept_jp': '財務活動によるキャッシュ・フロー',
  'value': '-14310000000',
  'unit': 'JPY',
  'context': 'Prior4YearDuration',
  'context_YYYY': '2020',
  'context_NCM': False},
 {'concept': 'NetCashProvidedByUsedInFinancingActivitiesSummaryOfBusinessResults',
  'concept_jp': '財務活動によるキャッシュ・フロー',
  'value': '-34337000000',
  'unit': 'JPY',
  'context': 'Prior3YearDuration',
  'context_YYYY': '2021',
  'context_NCM': False},
 {'concept': 'NetCashProvidedByUsedInFinancingActivitiesSummaryOfBusinessResults',
  'concept_jp': '財務活動によるキャッシュ・フロー',
  'value': '-4483000000',
  'unit': 'JPY',
  'context': 'Prior2YearDuration',
  'context_YYYY': '2022',
  'context_NCM': False},
 {'concept': 'NetCashProvidedByUsedInFinancingActivitiesSummaryOfBusinessResults',
  'concept_jp': '財務活動によるキャッシュ・フロー',
  'value': '-7954000000',
  'unit': 'JPY',
  'context': 'Prior1YearDuration',
  'context_YYYY': '2023',
  'context_NCM': False},
 {'concept': 'NetCashProvidedByUsedInFinancingActivitiesSummaryOfBusinessResults',
  'concept_jp': '財務活動によるキャッシュ・フロー',
  'value': '-6280000000',
  'unit': 'JPY',
  'context': 'CurrentYearDuration',
  'context_YYYY': '2024',
  'context_NCM': False},
 {'concept': 'CashAndCashEquivalentsSummaryOfBusinessResults',
  'concept_jp': '現金及び現金同等物の残高',
  'value': '934088000000',
  'unit': 'JPY',
  'context': 'Prior4YearInstant',
  'context_YYYY': '2020',
  'context_NCM': False},
 {'concept': 'CashAndCashEquivalentsSummaryOfBusinessResults',
  'concept_jp': '現金及び現金同等物の残高',
  'value': '2012295000000',
  'unit': 'JPY',
  'context': 'Prior3YearInstant',
  'context_YYYY': '2021',
  'context_NCM': False},
 {'concept': 'CashAndCashEquivalentsSummaryOfBusinessResults',
  'concept_jp': '現金及び現金同等物の残高',
  'value': '1750676000000',
  'unit': 'JPY',
  'context': 'Prior2YearInstant',
  'context_YYYY': '2022',
  'context_NCM': False},
 {'concept': 'CashAndCashEquivalentsSummaryOfBusinessResults',
  'concept_jp': '現金及び現金同等物の残高',
  'value': '1201299000000',
  'unit': 'JPY',
  'context': 'Prior1YearInstant',
  'context_YYYY': '2023',
  'context_NCM': False},
 {'concept': 'CashAndCashEquivalentsSummaryOfBusinessResults',
  'concept_jp': '現金及び現金同等物の残高',
  'value': '1359724000000',
  'unit': 'JPY',
  'context': 'CurrentYearInstant',
  'context_YYYY': '2024',
  'context_NCM': False},
 {'concept': 'NumberOfEmployees',
  'concept_jp': '従業員数',
  'value': '2282',
  'unit': 'pure',
  'context': 'Prior4YearInstant',
  'context_YYYY': '2020',
  'context_NCM': False},
 {'concept': 'NumberOfEmployees',
  'concept_jp': '従業員数',
  'value': '2286',
  'unit': 'pure',
  'context': 'Prior3YearInstant',
  'context_YYYY': '2021',
  'context_NCM': False},
 {'concept': 'NumberOfEmployees',
  'concept_jp': '従業員数',
  'value': '2271',
  'unit': 'pure',
  'context': 'Prior2YearInstant',
  'context_YYYY': '2022',
  'context_NCM': False},
 {'concept': 'NumberOfEmployees',
  'concept_jp': '従業員数',
  'value': '2198',
  'unit': 'pure',
  'context': 'Prior1YearInstant',
  'context_YYYY': '2023',
  'context_NCM': False},
 {'concept': 'NumberOfEmployees',
  'concept_jp': '従業員数',